[Keyboard] Add Keychron K2v2 RGB ISO
SonixQMK/qmk_firmware pull request #358
Opened 2023-10-18 10:54 UTC by KeijoMika

## Description

Add Keychron K2v2 RGB ISO keyboard to sn32_develop

Based on previous work of @dexter93 on the K2, @PythonDeployer and @ephb on the K4, and @tbowmo on the K8. Guidance also provided by @karliss.

I just transferred some settings to info.json and added VIA support. Layout file also provided for VIA.

## Supported
- [x] RGB
- [x] VIA
- [ ] Full original functionality (Bluetooth not working)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-18 11:52 UTC, dexter93 requested changes

2023-10-18 11:52 UTC, dexter93 commented on keyboards/keychron/k2/rgb/v2/iso/keymaps/via/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 4
```suggestion
```
default is 4. no need to declare again

2023-10-18 11:52 UTC, dexter93 commented on keyboards/keychron/k2/rgb/v2/iso/keymaps/via/config.h
> +#define VIA_QMK_RGBLIGHT_ENABLE
```suggestion
```
this flag is obsolete. it's been removed.

2023-10-18 11:53 UTC, dexter93 commented on keyboards/keychron/k2/rgb/v2/iso/keymaps/via/config.h
> +#define VIA_QMK_RGBLIGHT_ENABLE
the entire file can be safely removed

2023-10-18 12:17 UTC, KeijoMika commented on keyboards/keychron/k2/rgb/v2/iso/keymaps/via/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 4
Thank you. Removed keyboards/keychron/k2/rgb/v2/iso/keymaps/via/config.h

2023-10-21 06:33 UTC, dexter93 requested changes

2023-10-21 06:33 UTC, dexter93 commented on keyboards/keychron/k2/rgb/v2/iso/readme.md
> +* **Physical Bootloader Pins**: Turn off the keyboard, Using a pair of tweezers or a paperclip, short the 2 pins left from spacebar switch holes and hold the tweezers on the pins while turning the ke
```suggestion
Enter the bootloader in 2 ways:

* **Physical Bootloader Pins**: Turn off the keyboard, Using a pair of tweezers or a paperclip, short the 2 pins left from spacebar switch holes and hold the tweezers on the pins while turning the keyboard on, this should put it into the bootloader.
* **Keycode in layout**: Press the key mapped to `QK_BOOT` if it is available. In the default keymap Fn+Esc.
```

2023-10-21 08:47 UTC, merged