Add Hator gravity tkl keyboard support
SonixQMK/qmk_firmware pull request #389
Opened 2024-07-20 13:19 UTC by Matros1975

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ x] Keyboard (addition or update)
- [ x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-07-27 08:59 UTC, dexter93 requested changes
Hi, thank you for the PR. Please update the copyrights, follow the linter suggestions and fix build.

2024-07-27 08:59 UTC, dexter93 commented on keyboards/hator/gravity/tkl/config.h
> +// SPDX-License-Identifier: GPL-2.0-or-later
duplicate licence. Please either pick the short SPDX format or the full GPLv2+

2024-07-27 08:59 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keymaps/default/keymap.c
> +// SPDX-License-Identifier: GPL-2.0-or-later
licence

2024-07-27 08:59 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keymaps/via/config.h
> +#define VIA_QMK_RGBLIGHT_ENABLE
```suggestion
```
this is obsolete

2024-07-27 08:59 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keymaps/via/keymap.c
> +// SPDX-License-Identifier: GPL-2.0-or-later
licence

2024-07-27 08:59 UTC, dexter93 commented on keyboards/hator/gravity/tkl/readme.md
> +# skyfall
this readme is inconsistent with the rest of the keyboard tree. Please update

2024-07-27 08:59 UTC, dexter93 commented on keyboards/hator/gravity/tkl/rules.mk
> +WEAR_LEVELING_DRIVER = sn32_flash
```suggestion
```
this has been updated now. `sn32_flash` is no more

2024-07-27 08:59 UTC, dexter93 commented on keyboards/hator/gravity/tkl/info.json
> +			{ "matrix": [ 6, 1 ], "flags": 2, "x": 0, "y": 8 },
linting required.

2024-07-27 23:11 UTC, Matros1975 commented
All remarks are fixed. Please review

2024-07-28 09:49 UTC, dexter93 requested changes

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/rules.mk
> +ENCODER_MAP_ENABLE = yes
```suggestion
```
This fails lint. It should be moved in keymap level.

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/info.json
> +{
duplicate `info.json` and `keyboard.json` in the same directory makes no sense. Please remove this file

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/rules.mk
> +ENCODER_MAP_ENABLE = yes
Furthermore, since you have `keyboard.json` in the same directory, this file is safe to remove.

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keyboard.json
> +		"force_nkro": true
fix idents

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keyboard.json
> +		"encoder": true,
```suggestion
        "encoder": true,
```

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keyboard.json
> +		"rgb_matrix": true
```suggestion
        "rgb_matrix": true
```

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keyboard.json
> +			{ "matrix": [ 0, 13 ], "flags": 2, "x": 12, "y": 0 },
```suggestion
            { "matrix": [ 0, 13 ], "flags": 2, "x": 12, "y": 0 },
```

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keyboard.json
> +			{ "matrix": [ 6, 15 ], "flags": 2, "x": 223, "y": 56 }
```suggestion
            { "matrix": [ 6, 1 ], "flags": 2, "x": 0, "y": 8 },
            { "matrix": [ 6, 2 ], "flags": 2, "x": 0, "y": 16 },
            { "matrix": [ 6, 3 ], "flags": 2, "x": 0, "y": 24 },
            { "matrix": [ 6, 4 ], "flags": 2, "x": 0, "y": 32 },
            { "matrix": [ 6, 5 ], "flags": 2, "x": 0, "y": 40 },
            { "matrix": [ 6, 6 ], "flags": 2, "x": 0, "y": 48 },
            { "matrix": [ 6, 7 ], "flags": 2, "x": 0, "y": 56 },
            { "matrix": [ 6, 8 ], "flags": 2, "x": 216, "y": 0 },
            { "matrix": [ 6, 9 ], "flags": 2, "x": 217, "y": 8 },
            { "matrix": [ 6, 10 ], "flags": 2, "x": 218, "y": 16 },
            { "matrix": [ 6, 11 ], "flags": 2, "x": 219, "y": 24 },
            { "matrix": [ 6, 12 ], "flags": 2, "x": 220, "y": 32 },
            { "matrix": [ 6, 13 ], "flags": 2, "x": 221, "y": 40 },
            { "matrix": [ 6, 14 ], "flags": 2, "x": 222, "y": 48 },
            { "matrix": [ 6, 15 ], "flags": 2, "x": 223, "y": 56 }			
```

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keyboard.json
> +		"react_on_keyup": true,
```suggestion
        "react_on_keyup": true,
```

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keyboard.json
> +			    { "label": "NO_PIN", "matrix": [ 6, 15 ], "x": 17.5, "y": 7 }
spacing is also off here. Please fix it.

2024-07-28 09:49 UTC, dexter93 commented on keyboards/hator/gravity/tkl/readme.md
> +    qmk flash -kb hator/gravity/tkl -km via
`qmk flash` is not a supported feature at this point in time. Did you even test this?

2024-07-29 08:53 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keyboard.json
> +                { "label": "NO_PIN", "matrix": [ 6, 15 ], "x": 17.5, "y": 7 }
These look like underglow LEDs at the left and right side of the keyboard. Why are they declared as also being part of the key matrix?

2024-08-21 10:15 UTC, dexter93 requested changes

2024-08-21 10:15 UTC, dexter93 commented on keyboards/hator/gravity/tkl/keyboard.json
> +        "force_nkro": true
```suggestion
```
This will cause issues with BIOS. Please remove

2024-09-11 11:52 UTC, merged